<#
.SYNOPSIS
    Regenerates docs\intune-csp.md - the kit's baseline in Intune Settings
    catalog / Policy CSP terms, for teams that deliver policy that way
    instead of (or alongside) the remediation pack. Run after changing the
    settings table or tools\csp-map.psd1; CI fails if the committed page
    drifts.

.DESCRIPTION
    Items and values come from WinLogKit.Settings.ps1; the CSP names come
    from the curated tools\csp-map.psd1. Every kit item lands in exactly
    one of the two tables: covered by a CSP, or not (with the reason).

    Requires: Windows PowerShell 5.1+. No admin; writes only the doc page.
#>
[CmdletBinding()]
param(
    # Default resolved in the body: $PSScriptRoot is not reliably available
    # during param-default evaluation under powershell.exe -File.
    [string]$OutFile
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$kitRoot = Split-Path $PSScriptRoot -Parent
if ([string]::IsNullOrEmpty($OutFile)) { $OutFile = Join-Path (Join-Path $kitRoot 'docs') 'intune-csp.md' }

. (Join-Path $kitRoot 'WinLogKit.Settings.ps1')
. (Join-Path $kitRoot 'WinLogKit.Common.ps1')
$map = Import-PowerShellDataFile (Join-Path $PSScriptRoot 'csp-map.psd1')

$docBase = 'https://learn.microsoft.com/windows/client-management/mdm/'
# Link text is the CSP area (the part before the slash), as Microsoft titles the page.
function Format-Doc([string]$Page, [string]$Csp) {
    "[$(($Csp -split '/')[0])]($docBase$Page)"
}
function Format-Name([string]$Name, [string]$Scope) {
    if ($Scope -eq 'DomainController') { return "$Name (DC)" }
    return $Name
}
$auditText = @{ 1 = 'Success'; 2 = 'Failure'; 3 = 'Success+Failure' }

$covered = New-Object System.Collections.Generic.List[string]
$notCovered = New-Object System.Collections.Generic.List[string]
$auditMap = @{}; foreach ($k in $map.Audit.Keys) { $auditMap[$k.ToUpper()] = $map.Audit[$k] }

foreach ($sub in $script:BaselineAuditSubcategories) {
    $csp = $auditMap[$sub.Guid.ToUpper()]
    if ($null -eq $csp) { throw "No Audit CSP mapped for $($sub.Name) ($($sub.Guid)) in tools\csp-map.psd1." }
    $v = Get-AuditSettingValue $sub.Success $sub.Failure
    $covered.Add("| $(Format-Name $sub.Name $sub.Scope) | Audit | $($sub.Tier) | ``Audit/$csp`` | $v ($($auditText[$v])) | $(Format-Doc 'policy-csp-audit' 'Audit') |")
}

foreach ($rs in $script:BaselineRegistrySettings) {
    $label = Format-Name $rs.Id $rs.Scope
    if ($map.Registry.ContainsKey($rs.Id)) {
        $m = $map.Registry[$rs.Id]
        $covered.Add("| $label | Registry | $($rs.Tier) | ``$($m.Csp)`` | $($m.Value) | $(Format-Doc $m.Doc $m.Csp) |")
    } elseif ($map.NoCsp.ContainsKey($rs.Id)) {
        $notCovered.Add("| $label | Registry | $($map.NoCsp[$rs.Id]) |")
    } else {
        throw "Registry item $($rs.Id) is in neither Registry nor NoCsp in tools\csp-map.psd1."
    }
}

foreach ($ch in $script:BaselineChannels) {
    $kb = [long]($ch.TargetBytes / 1KB)
    if ($map.Channels.ContainsKey($ch.Name)) {
        $covered.Add("| $($ch.Name) | Log size | $($ch.Tier) | ``$($map.Channels[$ch.Name])`` | Enabled, $kb KB | $(Format-Doc 'policy-csp-eventlogservice' 'EventLogService') |")
    } else {
        $what = 'size'; if ($ch.MustEnable) { $what = 'size or enablement' }
        $notCovered.Add("| $($ch.Name) | Log | No CSP for this log's $what. |")
    }
}

foreach ($sa in $script:BaselineSmbAuditSettings) {
    $notCovered.Add("| $($sa.Id) | SMB audit | No CSP. Set with ``Set-Smb$($sa.Side)Configuration`` (Windows Server 2025 and later). |")
}
$notCovered.Add("| $($script:BaselineAdcsAuditFilter.Id) | Registry | No CSP, and it needs a CertSvc restart: set it on the CA in a change window (``Enable-LoggingBaseline.ps1`` there). |")

# ---- write the page ---------------------------------------------------------

$header = @'
# Intune Settings catalog

<!-- GENERATED by tools\Export-CspTable.ps1 - do not edit by hand.
     CI fails if this page drifts from the settings table and tools\csp-map.psd1. -->

If you deliver policy through the Intune **Settings catalog** rather than
scripts, this is the kit's baseline in those terms. Settings catalog
settings are backed by Microsoft's
[Policy CSPs](https://learn.microsoft.com/windows/client-management/mdm/policy-configuration-service-provider);
each row names the CSP and links its Microsoft page. Find the setting in
the catalog by its name, or set it as a custom OMA-URI:
`./Device/Vendor/MSFT/Policy/Config/<CSP>`.

!!! note
    Built from Microsoft's CSP documentation, not yet field-tested in a
    tenant ([#46](https://github.com/spydisec/WinLogKit/issues/46)). Pilot
    on a small device group and check the result with
    `Test-LoggingBaseline.ps1`.

Things to know before you start:

- **The catalog only covers part of the baseline.** Audit policy,
  command-line capture, Windows PowerShell logging and three log sizes
  have a CSP. Everything in the second table doesn't: keep the
  [remediation pack](deployment.md#intune-workstations-and-cloud-managed-servers)
  for those. The two work together, because the pack only changes what is
  below the baseline and the values here match it.
- **CSPs aren't role-aware.** Rows marked **(DC)** only matter on domain
  controllers; the remediation pack checks the role on each host, a
  Settings catalog profile applies to everything it's assigned to.
- **A policy sets a log size outright.** The kit only ever raises sizes;
  a size policy also lowers a log that was bigger. Set the larger value
  if your hosts already have one.
- **Mind the Tier column.** Leave HighVolume rows out unless you apply
  that tier (see [Baselines](baselines.md)).

## Settings with a CSP

| Setting | Type | Tier | CSP | Value | Microsoft doc |
|---|---|---|---|---|---|
'@

$middle = @'

## Settings without a CSP

Use the remediation pack for these. The AD CS row is the exception, as
noted.

| Setting | Type | Why |
|---|---|---|
'@

# Here-strings drop their final newline: add it, or the first row would
# concatenate onto the table separator.
$content = $header + "`n" + ($covered -join "`n") + "`n" + $middle + "`n" + ($notCovered -join "`n") + "`n"
[System.IO.File]::WriteAllText($OutFile, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Settings catalog page written: $OutFile ($($covered.Count) with a CSP, $($notCovered.Count) without)"
exit 0
